namespace P2W.DealFinder.Application.Grading;

public sealed record GradedScanDefaults(
    string[] Grades,
    int PagesPerGrade,
    int Take,
    bool ShowOnlyPassingDeals,
    bool IncludeBuyNow,
    bool IncludeAuctions,
    string EbayCategoryId,
    string EbayCategoryName,
    string EbayConditionId,
    string EbayConditionName,
    decimal MinMarketValue,
    decimal MaxMarketValue,
    decimal MinEffectiveBuyPrice,
    decimal MaxEffectiveBuyPrice,
    decimal MinProfit,
    decimal MinMarginPercent,
    decimal MinRoiPercent,
    int MinMatchScore,
    int MinProductYearlyVolume,
    decimal FeePercent,
    decimal FixedFee,
    decimal OutboundShippingCost,
    decimal PackingCost,
    decimal BufferCost)
{
    public static GradedScanDefaults Default { get; } = new(
        GradeDefinitions.DefaultScanGrades.Select(x => x.Code).ToArray(),
        1,
        100,
        false,
        true,
        false,
        EbaySearchScope.DefaultPokemonCards.CategoryId,
        EbaySearchScope.DefaultPokemonCards.CategoryName,
        EbaySearchScope.DefaultPokemonCards.ConditionId,
        EbaySearchScope.DefaultPokemonCards.ConditionName,
        50m,
        250m,
        10m,
        250m,
        10m,
        10m,
        10m,
        75,
        0,
        13.25m,
        0.30m,
        5.00m,
        1.00m,
        2.00m);
}
